### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by psagne** [KULeuven-CCIS/idp-authn-jwt#2]
Hi,

It is difficult to correctly track versions of the project, and manage updates because the version is always "1.0-LATEST-SNAPSHOT" in the pom.xml.

 Could you increment the version when you publish an update?

Thanks for this really helpful implementation anyways.

**Comment by gueuselambix** [comment]
Fully agree, so I have tagged this first version with v1.0.0 now.
The master branch will still be 1.0-LATEST-SNAPSHOT
