### ISSUE TITLE
idp-utils artefact cannot be found in main maven repository

### ISSUE THREAD

**Issue by tbrandstetter** [KULeuven-CCIS/idp-authn-jwt#4]
It's not possible to build the latest version, because of the non available "idp-util" artefact, which was implemented in the latest build.

**Comment by gueuselambix** [comment]
Hi
I was too quick to push my commits to github. I plan to externalize the JWTProcessor class to another maven artifact, which can be reused by other classes. Before I can do this, I have to publish this lib to some public maven repo, which I have not done before. 
I have reverted my changes on the master branch and I have created a tag v1.0.0 which successfully builds now.
